name: Sunday
options:
  bundleIdPrefix: jh.sunday
  deploymentTarget:
    iOS: 17.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: jh.sunday.app
    MARKETING_VERSION: 1.1.2
    CURRENT_PROJECT_VERSION: 3
    DEVELOPMENT_TEAM: 3AP9XN3Q4V
targets:
  Sunday:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
      - path: SundayActivityAttributes.swift
    resources:
      - path: Resources/Assets.xcassets
        buildPhase: resources
      - path: Resources/LaunchScreen.storyboard
    info:
      path: Resources/Info.plist
      properties:
        NSSupportsLiveActivities: YES
        CFBundleDisplayName: Get the D
        LSApplicationCategoryType: public.app-category.healthcare-fitness
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        NSLocationWhenInUseUsageDescription: "Get the D needs your location to determine UV levels at your current position"
        NSLocationAlwaysAndWhenInUseUsageDescription: "Get the D needs your location to track UV exposure throughout the day"
        NSHealthShareUsageDescription: "Get the D reads your health data to provide personalized vitamin D recommendations"
        NSHealthUpdateUsageDescription: "Get the D saves your vitamin D intake data to Health app"
        UIUserInterfaceStyle: Light
        UIBackgroundModes:
          - location
        NSUserNotificationCenterUsageDescription: "Get the D sends reminders for sunrise, sunset, and solar noon to help you track vitamin D"
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - sunday
            CFBundleURLName: com.jh.sunday
        # This key is required by App Store Connect
        CFBundleIconName: AppIcon
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        ENABLE_PREVIEWS: YES
        CODE_SIGN_ENTITLEMENTS: Resources/Sunday.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
    capabilities:
      - com.apple.HealthKit
      - com.apple.BackgroundModes:
          enabled: true
          modes:
            - location
            - processing
      - com.apple.ApplicationGroups:
          enabled: true
          groups:
            - group.jh.sunday.widget
    dependencies:
      - target: SundayWidget
  SundayWidget:
    type: app-extension
    platform: iOS
    sources:
      - SundayWidget
      - path: SundayWidget/LiveActivityWidget.swift
      - path: SundayActivityAttributes.swift
    resources:
      - SundayWidget/Assets.xcassets
    info:
      path: SundayWidget/Info.plist
      properties:
        CFBundleDisplayName: Get the D Widget
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jh.sunday.app.widget
        INFOPLIST_FILE: SundayWidget/Info.plist
        SKIP_INSTALL: true
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_ENTITLEMENTS: SundayWidget/SundayWidget.entitlements
    capabilities:
      - com.apple.ApplicationGroups:
          enabled: true
          groups:
            - group.jh.sunday.widget
schemes:
  Sunday:
    build:
      targets:
        Sunday: all
        SundayWidget: all